name: first1

on: push
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  ubuntu: 
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    runs-on: windows-latest
    steps:
    - run: date
  depends:
    needs: [windows, ubuntu, macos]
    runs-on: windows-latest
    steps:
    - run: ls -l
